[package]
name = 'rudis-server'
version = '0.1.0'
edition = '2021'

[dependencies]
anyhow = { workspace = true }
rudis = { workspace = true }
macro_rules_attribute = '0.2'
smol = '2'
smol-macros = '0.1'
