on: push
name: Lints and tests
jobs:
  lints-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo build --release
      - run: cargo test --release
      - run: cargo clippy
